/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { CreateFileRoute, FileRoutesByPath } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedLayoutRouteRouteImport } from './routes/_unauthenticatedLayout/route'
import { Route as AuthenticatedLayoutRouteRouteImport } from './routes/_authenticatedLayout/route'
import { Route as AuthenticatedLayoutIndexRouteImport } from './routes/_authenticatedLayout/index'
import { Route as UnauthenticatedLayoutSignUpRouteImport } from './routes/_unauthenticatedLayout/sign-up'
import { Route as UnauthenticatedLayoutSignInRouteImport } from './routes/_unauthenticatedLayout/sign-in'

const UnauthenticatedLayoutRouteRoute =
  UnauthenticatedLayoutRouteRouteImport.update({
    id: '/_unauthenticatedLayout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLayoutRouteRoute =
  AuthenticatedLayoutRouteRouteImport.update({
    id: '/_authenticatedLayout',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLayoutIndexRoute =
  AuthenticatedLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLayoutRouteRoute,
  } as any)
const UnauthenticatedLayoutSignUpRoute =
  UnauthenticatedLayoutSignUpRouteImport.update({
    id: '/sign-up',
    path: '/sign-up',
    getParentRoute: () => UnauthenticatedLayoutRouteRoute,
  } as any)
const UnauthenticatedLayoutSignInRoute =
  UnauthenticatedLayoutSignInRouteImport.update({
    id: '/sign-in',
    path: '/sign-in',
    getParentRoute: () => UnauthenticatedLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof UnauthenticatedLayoutSignInRoute
  '/sign-up': typeof UnauthenticatedLayoutSignUpRoute
  '/': typeof AuthenticatedLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof UnauthenticatedLayoutSignInRoute
  '/sign-up': typeof UnauthenticatedLayoutSignUpRoute
  '/': typeof AuthenticatedLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticatedLayout': typeof AuthenticatedLayoutRouteRouteWithChildren
  '/_unauthenticatedLayout': typeof UnauthenticatedLayoutRouteRouteWithChildren
  '/_unauthenticatedLayout/sign-in': typeof UnauthenticatedLayoutSignInRoute
  '/_unauthenticatedLayout/sign-up': typeof UnauthenticatedLayoutSignUpRoute
  '/_authenticatedLayout/': typeof AuthenticatedLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/sign-up' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/sign-up' | '/'
  id:
    | '__root__'
    | '/_authenticatedLayout'
    | '/_unauthenticatedLayout'
    | '/_unauthenticatedLayout/sign-in'
    | '/_unauthenticatedLayout/sign-up'
    | '/_authenticatedLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedLayoutRouteRoute: typeof AuthenticatedLayoutRouteRouteWithChildren
  UnauthenticatedLayoutRouteRoute: typeof UnauthenticatedLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticatedLayout': {
      id: '/_authenticatedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticatedLayout': {
      id: '/_unauthenticatedLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticatedLayout/sign-in': {
      id: '/_unauthenticatedLayout/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof UnauthenticatedLayoutSignInRouteImport
      parentRoute: typeof UnauthenticatedLayoutRouteRoute
    }
    '/_unauthenticatedLayout/sign-up': {
      id: '/_unauthenticatedLayout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof UnauthenticatedLayoutSignUpRouteImport
      parentRoute: typeof UnauthenticatedLayoutRouteRoute
    }
    '/_authenticatedLayout/': {
      id: '/_authenticatedLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedLayoutIndexRouteImport
      parentRoute: typeof AuthenticatedLayoutRouteRoute
    }
  }
}

declare module './routes/_authenticatedLayout/route' {
  const createFileRoute: CreateFileRoute<
    '/_authenticatedLayout',
    FileRoutesByPath['/_authenticatedLayout']['parentRoute'],
    FileRoutesByPath['/_authenticatedLayout']['id'],
    FileRoutesByPath['/_authenticatedLayout']['path'],
    FileRoutesByPath['/_authenticatedLayout']['fullPath']
  >
}
declare module './routes/_unauthenticatedLayout/route' {
  const createFileRoute: CreateFileRoute<
    '/_unauthenticatedLayout',
    FileRoutesByPath['/_unauthenticatedLayout']['parentRoute'],
    FileRoutesByPath['/_unauthenticatedLayout']['id'],
    FileRoutesByPath['/_unauthenticatedLayout']['path'],
    FileRoutesByPath['/_unauthenticatedLayout']['fullPath']
  >
}
declare module './routes/_unauthenticatedLayout/sign-in' {
  const createFileRoute: CreateFileRoute<
    '/_unauthenticatedLayout/sign-in',
    FileRoutesByPath['/_unauthenticatedLayout/sign-in']['parentRoute'],
    FileRoutesByPath['/_unauthenticatedLayout/sign-in']['id'],
    FileRoutesByPath['/_unauthenticatedLayout/sign-in']['path'],
    FileRoutesByPath['/_unauthenticatedLayout/sign-in']['fullPath']
  >
}
declare module './routes/_unauthenticatedLayout/sign-up' {
  const createFileRoute: CreateFileRoute<
    '/_unauthenticatedLayout/sign-up',
    FileRoutesByPath['/_unauthenticatedLayout/sign-up']['parentRoute'],
    FileRoutesByPath['/_unauthenticatedLayout/sign-up']['id'],
    FileRoutesByPath['/_unauthenticatedLayout/sign-up']['path'],
    FileRoutesByPath['/_unauthenticatedLayout/sign-up']['fullPath']
  >
}
declare module './routes/_authenticatedLayout/index' {
  const createFileRoute: CreateFileRoute<
    '/_authenticatedLayout/',
    FileRoutesByPath['/_authenticatedLayout/']['parentRoute'],
    FileRoutesByPath['/_authenticatedLayout/']['id'],
    FileRoutesByPath['/_authenticatedLayout/']['path'],
    FileRoutesByPath['/_authenticatedLayout/']['fullPath']
  >
}

interface AuthenticatedLayoutRouteRouteChildren {
  AuthenticatedLayoutIndexRoute: typeof AuthenticatedLayoutIndexRoute
}

const AuthenticatedLayoutRouteRouteChildren: AuthenticatedLayoutRouteRouteChildren =
  {
    AuthenticatedLayoutIndexRoute: AuthenticatedLayoutIndexRoute,
  }

const AuthenticatedLayoutRouteRouteWithChildren =
  AuthenticatedLayoutRouteRoute._addFileChildren(
    AuthenticatedLayoutRouteRouteChildren,
  )

interface UnauthenticatedLayoutRouteRouteChildren {
  UnauthenticatedLayoutSignInRoute: typeof UnauthenticatedLayoutSignInRoute
  UnauthenticatedLayoutSignUpRoute: typeof UnauthenticatedLayoutSignUpRoute
}

const UnauthenticatedLayoutRouteRouteChildren: UnauthenticatedLayoutRouteRouteChildren =
  {
    UnauthenticatedLayoutSignInRoute: UnauthenticatedLayoutSignInRoute,
    UnauthenticatedLayoutSignUpRoute: UnauthenticatedLayoutSignUpRoute,
  }

const UnauthenticatedLayoutRouteRouteWithChildren =
  UnauthenticatedLayoutRouteRoute._addFileChildren(
    UnauthenticatedLayoutRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedLayoutRouteRoute: AuthenticatedLayoutRouteRouteWithChildren,
  UnauthenticatedLayoutRouteRoute: UnauthenticatedLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
